name: computer_status_reporter
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  http: ^1.2.1
  country_flags: ^2.0.1
  fluttertoast: ^8.0.9
  qr_flutter: ^4.1.0
  printing: ^5.4.0
  pdf: ^3.10.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
